### PR TITLE
Add Create Feature to UI

### PR DESCRIPTION
**Pull request by Zoey367**
Made the following changes: 
- Added Create a scenario for BDD test in `recommendations.feature`
- Enables a function to make "I enter "{value}" in the "{field_name}" field" work

### CODE REVIEW

**Comment by muyunli123** [comment]
Hi Yihong, 

I noticed that you added a new function to enter values in the input box. I wonder if that is because the set function that already existed in the code doesn't work for inputting values. Because when I implemented the Query feature, I found that the set function is used to input values and the select function is used to select value from dropdown (as the example I copied below). 
> And I set the "Name" to "Happy"
> And I set the "Category" to "Hippo"
> And I select "False" in the "Available" dropdown
> And I select "Male" in the "Gender" dropdown

**Comment by Zoey367** [comment]
Yes! Because I am not sure will the old function work well when enter
integers. They use set as you wrote but all of them are string. I don’t
mind change to the old one if they work!

**Comment by muyunli123** [comment]
> Yes! Because I am not sure will the old function work well when enter integers. They use set as you wrote but all of them are string. I don’t mind change to the old one if they work!
> […](#)
> On Thu, Nov 14, 2024 at 18:06 Muyun Li ***@***.***> wrote: Hi Yihong, I noticed that you added a new function to enter values in the input box. I wonder if that is because the set function that already existed in the code doesn't work for inputting values. Because when I implemented the Query feature, I found that the set function is used to input values and the select function is used to select value from dropdown (as the example I copied below). And I set the "Name" to "Happy" And I set the "Category" to "Hippo" And I select "False" in the "Available" dropdown And I select "Male" in the "Gender" dropdown — Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CSCI-2DGA-2D2820-2DFA24-2D003_recommendations_pull_72-23issuecomment-2D2477587495&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=8gynJW5BsFD_0D6-aDBH1A&m=UewLSF8a-Oyf2TlriGi1C_J5VTBI4ITVioL2pWhetHYzUDotcE_mIS2j9CtHrhQY&s=LSTuXUgx0tAUlNCD4-1_dFtC0LBe--_hQqy_8lVYZj8&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BDZJDMTG3KT2OCQH2XUZCND2AUUI3AVCNFSM6AAAAABRZU74K6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINZXGU4DONBZGU&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=8gynJW5BsFD_0D6-aDBH1A&m=UewLSF8a-Oyf2TlriGi1C_J5VTBI4ITVioL2pWhetHYzUDotcE_mIS2j9CtHrhQY&s=hHfiEJTPlIzmmO8kd6i4gD_Dr4Tv9-ndp2oICh3T1GA&e=> . You are receiving this because you authored the thread.Message ID: ***@***.***>

I think it should work for integers but you can check that. Product id and recommended id (and like & dislike as well) parsed from the query string are transformed into integers as in line 55 of recommendation_steps.py.

**Comment by muyunli123** [comment]
And also, since the recommendation type and status are set to be selections instead of input box on the UI, the corresponding features should be like below otherwise the `behave` would fail:
```
And I select "False" in the "Available" dropdown
And I select "Male" in the "Gender" dropdown
```

**Comment by Zoey367** [comment]
Ok I see. I‘ll change it together when I add delete to feature. Thank you
so much for your help!

**Comment by muyunli123** [comment]
> Ok I see. I‘ll change it together when I add delete to feature. Thank you so much for your help!
> […](#)
> On Thu, Nov 14, 2024 at 22:52 Muyun Li ***@***.***> wrote: Yes! Because I am not sure will the old function work well when enter integers. They use set as you wrote but all of them are string. I don’t mind change to the old one if they work! … <#m_6548792688485410549_m_2419869057336449914_> On Thu, Nov 14, 2024 at 18:06 Muyun Li *@*.*> wrote: Hi Yihong, I noticed that you added a new function to enter values in the input box. I wonder if that is because the set function that already existed in the code doesn't work for inputting values. Because when I implemented the Query feature, I found that the set function is used to input values and the select function is used to select value from dropdown (as the example I copied below). And I set the "Name" to "Happy" And I set the "Category" to "Hippo" And I select "False" in the "Available" dropdown And I select "Male" in the "Gender" dropdown — Reply to this email directly, view it on GitHub https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CSCI-2DGA-2D2820-2DFA24-2D003_recommendations_pull_72-23issuecomment-2D2477587495&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=8gynJW5BsFD_0D6-aDBH1A&m=UewLSF8a-Oyf2TlriGi1C_J5VTBI4ITVioL2pWhetHYzUDotcE_mIS2j9CtHrhQY&s=LSTuXUgx0tAUlNCD4-1_dFtC0LBe--_hQqy_8lVYZj8&e= <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CSCI-2DGA-2D2820-2DFA24-2D003_recommendations_pull_72-23issuecomment-2D2477587495&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=8gynJW5BsFD_0D6-aDBH1A&m=UewLSF8a-Oyf2TlriGi1C_J5VTBI4ITVioL2pWhetHYzUDotcE_mIS2j9CtHrhQY&s=LSTuXUgx0tAUlNCD4-1_dFtC0LBe--_hQqy_8lVYZj8&e=>, or unsubscribe https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BDZJDMTG3KT2OCQH2XUZCND2AUUI3AVCNFSM6AAAAABRZU74K6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINZXGU4DONBZGU&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=8gynJW5BsFD_0D6-aDBH1A&m=UewLSF8a-Oyf2TlriGi1C_J5VTBI4ITVioL2pWhetHYzUDotcE_mIS2j9CtHrhQY&s=hHfiEJTPlIzmmO8kd6i4gD_Dr4Tv9-ndp2oICh3T1GA&e= <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BDZJDMTG3KT2OCQH2XUZCND2AUUI3AVCNFSM6AAAAABRZU74K6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINZXGU4DONBZGU&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=8gynJW5BsFD_0D6-aDBH1A&m=UewLSF8a-Oyf2TlriGi1C_J5VTBI4ITVioL2pWhetHYzUDotcE_mIS2j9CtHrhQY&s=hHfiEJTPlIzmmO8kd6i4gD_Dr4Tv9-ndp2oICh3T1GA&e=> . You are receiving this because you authored the thread.Message ID: @.*> I think it should work for integers but you can check that. Product id and recommended id (and like & dislike as well) parsed from the query string are transformed into integers as in line 55 of recommendation_steps.py. — Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CSCI-2DGA-2D2820-2DFA24-2D003_recommendations_pull_72-23issuecomment-2D2477899088&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=8gynJW5BsFD_0D6-aDBH1A&m=NIRj1pLy_MxCTwNHoKWHsnKpD10M4dSqF-IYKi-YEPJ9XdEMQn_TdpKyKI0vEmZG&s=KiS8h9s1EFsW3ZM_3I36zKWflofHNTi059A6poxc7Fs&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BDZJDMR7ZHXR4VSCHAD4TVD2AVVWLAVCNFSM6AAAAABRZU74K6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINZXHA4TSMBYHA&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=8gynJW5BsFD_0D6-aDBH1A&m=NIRj1pLy_MxCTwNHoKWHsnKpD10M4dSqF-IYKi-YEPJ9XdEMQn_TdpKyKI0vEmZG&s=iZuNbyXuv5QnucgJUecM1QY3xzPWWyJTacLs18yjFlY&e=> . You are receiving this because you authored the thread.Message ID: ***@***.***>

could you change the Create related part within this PR? so that we can close this issue and won't make your next PR connected to 2 issues

**Comment by muyunli123** [comment]
I see that you changed the steps back to "set". Did you check if the `behave` had passed? If yes then we are good to merge this PR.

**Comment by Zoey367** [comment]
> I see that you changed the steps back to "set". Did you check if the `behave` had passed? If yes then we are good to merge this PR.

**Pull request merged**
